### ISSUE TITLE
Supply an example with g++?

### ISSUE THREAD

**Issue by richelbilderbeek** [codecov/example-c#2]
The example shown in `README.md` shows a `clang` example. Does `codecov` also work with `g++`? If yes, could you please add an example? Would be cool, `codecov` is IMHO great!

**Comment by stevepeak** [comment]
Hey @richelbilderbeek perhaps you can work on the example with me (as I'm not familiar with `g++`)?

From what I gather you can produce an `lcov` report for `g++`, which is accepted by Codecov. I'm not familiar with how, but would love to learn more. Thank you!

**Comment by richelbilderbeek** [comment]
I have been working on a minimal example at https://github.com/richelbilderbeek/qmake-cpp11 , which uses Travis CI that call CodeCov, and uses qmake as a build system. You can see there its code coverage is 'unknown'. If you want to have a go at it, I can offer you to become a collaborator of that GitHub. I will also have a go at it soon.

**Comment by richelbilderbeek** [comment]
I have added you as a collaborator, just in case :-)

**Comment by richelbilderbeek** [comment]
I got a C++98 working example at https://github.com/richelbilderbeek/qmake_gcov !

**Comment by richelbilderbeek** [comment]
With C++11: https://github.com/richelbilderbeek/cpp11_qmake_gcov
With C++11 and Boost: https://github.com/richelbilderbeek/cpp11_qmake_boost_gcov

This one does not work as expected:
With C++11 and Boost and a bigger project: https://github.com/richelbilderbeek/cpp11_qmake_boost_gcov_bigger_project

**Comment by realvictorprm** [comment]
Is this completed now?

**Comment by richelbilderbeek** [comment]
I think this indeed should be closed now :+1:
